//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpgTimerWeb2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpgTimerWeb2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   /*!
        /// * Bootstrap v3.3.6 (http://getbootstrap.com)
        /// * Copyright 2011-2015 Twitter, Inc.
        /// * Licensed under the MIT license
        /// */
        ///if(&quot;undefined&quot;==typeof jQuery)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery&quot;);+function(a){&quot;use strict&quot;;var b=a.fn.jquery.split(&quot; &quot;)[0].split(&quot;.&quot;);if(b[0]&lt;2&amp;&amp;b[1]&lt;9||1==b[0]&amp;&amp;9==b[1]&amp;&amp;b[2]&lt;1||b[0]&gt;2)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3&quot;)}(jQuery),+function(a){&quot;use strict&quot;;function b(){var a=document.createE [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BootStrap {
            get {
                return ResourceManager.GetString("BootStrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;version&quot;:3,&quot;sources&quot;:[&quot;less/normalize.less&quot;,&quot;less/print.less&quot;,&quot;bootstrap.css&quot;,&quot;dist/css/bootstrap.css&quot;,&quot;less/glyphicons.less&quot;,&quot;less/scaffolding.less&quot;,&quot;less/mixins/vendor-prefixes.less&quot;,&quot;less/mixins/tab-focus.less&quot;,&quot;less/mixins/image.less&quot;,&quot;less/type.less&quot;,&quot;less/mixins/text-emphasis.less&quot;,&quot;less/mixins/background-variant.less&quot;,&quot;less/mixins/text-overflow.less&quot;,&quot;less/code.less&quot;,&quot;less/grid.less&quot;,&quot;less/mixins/grid.less&quot;,&quot;less/mixins/grid-framework.less&quot;,&quot;less/tables.less&quot;,&quot;less/mixins/table-row.less&quot;,&quot;less/form [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BootStrapCssMap {
            get {
                return ResourceManager.GetString("BootStrapCssMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /*!
        /// * Bootstrap v3.3.6 (http://getbootstrap.com)
        /// * Copyright 2011-2015 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-align:b [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BootStrapStyle {
            get {
                return ResourceManager.GetString("BootStrapStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /*! DataTables Bootstrap 3 integration
        /// * ©2011-2014 SpryMedia Ltd - datatables.net/license
        /// */
        ///
        ////**
        /// * DataTables integration for Bootstrap 3. This requires Bootstrap 3 and
        /// * DataTables 1.10 or newer.
        /// *
        /// * This file sets the defaults and adds options to DataTables to style its
        /// * controls using Bootstrap. See http://datatables.net/manual/styling/bootstrap
        /// * for further information.
        /// */
        ///(function(window, document, undefined){
        ///
        ///var factory = function( $, DataTable ) {
        ///&quot;use strict&quot;;
        ///
        ///
        ////*  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string dataTables_bootstrap {
            get {
                return ResourceManager.GetString("dataTables_bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_eot {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_eot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_svg {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_svg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_ttf {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_woff {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_woff2 {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_woff2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   /*! jQuery v2.1.3 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=a.document,m=&quot;2.1.3&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JQuery {
            get {
                return ResourceManager.GetString("JQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   div.dataTables_length label {
        ///	font-weight: normal;
        ///	text-align: left;
        ///	white-space: nowrap;
        ///}
        ///
        ///div.dataTables_length select {
        ///	width: 75px;
        ///	display: inline-block;
        ///}
        ///
        ///div.dataTables_filter {
        ///	text-align: right;
        ///}
        ///
        ///div.dataTables_filter label {
        ///	font-weight: normal;
        ///	white-space: nowrap;
        ///	text-align: left;
        ///}
        ///
        ///div.dataTables_filter input {
        ///	margin-left: 0.5em;
        ///	display: inline-block;
        ///}
        ///
        ///div.dataTables_info {
        ///	padding-top: 8px;
        ///	white-space: nowrap;
        ///}
        ///
        ///div.dataTables_paginate {        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string jquery_dataTables_css {
            get {
                return ResourceManager.GetString("jquery_dataTables_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /*! DataTables 1.10.4
        /// * ©2008-2014 SpryMedia Ltd - datatables.net/license
        /// */
        ///(function(Da,P,l){var O=function(g){function V(a){var b,c,e={};g.each(a,function(d){if((b=d.match(/^([^A-Z]+?)([A-Z])/))&amp;&amp;-1!==&quot;a aa ai ao as b fn i m o s &quot;.indexOf(b[1]+&quot; &quot;))c=d.replace(b[0],b[2].toLowerCase()),e[c]=d,&quot;o&quot;===b[1]&amp;&amp;V(a[d])});a._hungarianMap=e}function G(a,b,c){a._hungarianMap||V(a);var e;g.each(b,function(d){e=a._hungarianMap[d];if(e!==l&amp;&amp;(c||b[e]===l))&quot;o&quot;===e.charAt(0)?(b[e]||(b[e]={}),g.extend(!0,b[e],b[d]),G(a[ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string jqury_dataTables_js {
            get {
                return ResourceManager.GetString("jqury_dataTables_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap loader {
            get {
                object obj = ResourceManager.GetObject("loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;ja&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;script src=&quot;/js/jquery.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;/js/bootstrap.js&quot;&gt;&lt;/script&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/css/bootstrap.css&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, user-scalable=no&quot;&gt;
        ///    &lt;style&gt;
        ///        #user {
        ///            margin-bottom: -1px;
        ///            border-bottom-right-radius: 0;
        ///            border-bottom-left-ra [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap NotThumbnail {
            get {
                object obj = ResourceManager.GetObject("NotThumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
